// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entropy/configuration/parser/vm.proto

package entropy.configuration.parser;

public final class PBVirtualMachine {
  private PBVirtualMachine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class VirtualMachine extends
      com.google.protobuf.GeneratedMessage {
    // Use VirtualMachine.newBuilder() to construct.
    private VirtualMachine() {
      initFields();
    }
    private VirtualMachine(boolean noInit) {}
    
    private static final VirtualMachine defaultInstance;
    public static VirtualMachine getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public VirtualMachine getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entropy.configuration.parser.PBVirtualMachine.internal_static_VirtualMachine_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 nbOfCPUs = 2;
    public static final int NBOFCPUS_FIELD_NUMBER = 2;
    private boolean hasNbOfCPUs;
    private int nbOfCPUs_ = 0;
    public boolean hasNbOfCPUs() { return hasNbOfCPUs; }
    public int getNbOfCPUs() { return nbOfCPUs_; }
    
    // required int32 memoryConsumption = 3;
    public static final int MEMORYCONSUMPTION_FIELD_NUMBER = 3;
    private boolean hasMemoryConsumption;
    private int memoryConsumption_ = 0;
    public boolean hasMemoryConsumption() { return hasMemoryConsumption; }
    public int getMemoryConsumption() { return memoryConsumption_; }
    
    // required int32 cpuConsumption = 4;
    public static final int CPUCONSUMPTION_FIELD_NUMBER = 4;
    private boolean hasCpuConsumption;
    private int cpuConsumption_ = 0;
    public boolean hasCpuConsumption() { return hasCpuConsumption; }
    public int getCpuConsumption() { return cpuConsumption_; }
    
    // required int32 memoryDemand = 5;
    public static final int MEMORYDEMAND_FIELD_NUMBER = 5;
    private boolean hasMemoryDemand;
    private int memoryDemand_ = 0;
    public boolean hasMemoryDemand() { return hasMemoryDemand; }
    public int getMemoryDemand() { return memoryDemand_; }
    
    // required int32 cpuDemand = 6;
    public static final int CPUDEMAND_FIELD_NUMBER = 6;
    private boolean hasCpuDemand;
    private int cpuDemand_ = 0;
    public boolean hasCpuDemand() { return hasCpuDemand; }
    public int getCpuDemand() { return cpuDemand_; }
    
    private void initFields() {
    }
    @Override
	public final boolean isInitialized() {
      if (!hasName) return false;
      if (!hasNbOfCPUs) return false;
      if (!hasMemoryConsumption) return false;
      if (!hasCpuConsumption) return false;
      if (!hasMemoryDemand) return false;
      if (!hasCpuDemand) return false;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasNbOfCPUs()) {
        output.writeInt32(2, getNbOfCPUs());
      }
      if (hasMemoryConsumption()) {
        output.writeInt32(3, getMemoryConsumption());
      }
      if (hasCpuConsumption()) {
        output.writeInt32(4, getCpuConsumption());
      }
      if (hasMemoryDemand()) {
        output.writeInt32(5, getMemoryDemand());
      }
      if (hasCpuDemand()) {
        output.writeInt32(6, getCpuDemand());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasNbOfCPUs()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getNbOfCPUs());
      }
      if (hasMemoryConsumption()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getMemoryConsumption());
      }
      if (hasCpuConsumption()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getCpuConsumption());
      }
      if (hasMemoryDemand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getMemoryDemand());
      }
      if (hasCpuDemand()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getCpuDemand());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBVirtualMachine.VirtualMachine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(entropy.configuration.parser.PBVirtualMachine.VirtualMachine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private entropy.configuration.parser.PBVirtualMachine.VirtualMachine result;
      
      // Construct using entropy.configuration.parser.PBVirtualMachine.VirtualMachine.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new entropy.configuration.parser.PBVirtualMachine.VirtualMachine();
        return builder;
      }
      
      @Override
	protected entropy.configuration.parser.PBVirtualMachine.VirtualMachine internalGetResult() {
        return result;
      }
      
      @Override
	public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new entropy.configuration.parser.PBVirtualMachine.VirtualMachine();
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(result);
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDescriptor();
      }
      
      @Override
	public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getDefaultInstanceForType() {
        return entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance();
      }
      
      @Override
	public boolean isInitialized() {
        return result.isInitialized();
      }
      @Override
	public entropy.configuration.parser.PBVirtualMachine.VirtualMachine build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private entropy.configuration.parser.PBVirtualMachine.VirtualMachine buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      @Override
	public entropy.configuration.parser.PBVirtualMachine.VirtualMachine buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        entropy.configuration.parser.PBVirtualMachine.VirtualMachine returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entropy.configuration.parser.PBVirtualMachine.VirtualMachine) {
          return mergeFrom((entropy.configuration.parser.PBVirtualMachine.VirtualMachine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(entropy.configuration.parser.PBVirtualMachine.VirtualMachine other) {
        if (other == entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasNbOfCPUs()) {
          setNbOfCPUs(other.getNbOfCPUs());
        }
        if (other.hasMemoryConsumption()) {
          setMemoryConsumption(other.getMemoryConsumption());
        }
        if (other.hasCpuConsumption()) {
          setCpuConsumption(other.getCpuConsumption());
        }
        if (other.hasMemoryDemand()) {
          setMemoryDemand(other.getMemoryDemand());
        }
        if (other.hasCpuDemand()) {
          setCpuDemand(other.getCpuDemand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 16: {
              setNbOfCPUs(input.readInt32());
              break;
            }
            case 24: {
              setMemoryConsumption(input.readInt32());
              break;
            }
            case 32: {
              setCpuConsumption(input.readInt32());
              break;
            }
            case 40: {
              setMemoryDemand(input.readInt32());
              break;
            }
            case 48: {
              setCpuDemand(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required int32 nbOfCPUs = 2;
      public boolean hasNbOfCPUs() {
        return result.hasNbOfCPUs();
      }
      public int getNbOfCPUs() {
        return result.getNbOfCPUs();
      }
      public Builder setNbOfCPUs(int value) {
        result.hasNbOfCPUs = true;
        result.nbOfCPUs_ = value;
        return this;
      }
      public Builder clearNbOfCPUs() {
        result.hasNbOfCPUs = false;
        result.nbOfCPUs_ = 0;
        return this;
      }
      
      // required int32 memoryConsumption = 3;
      public boolean hasMemoryConsumption() {
        return result.hasMemoryConsumption();
      }
      public int getMemoryConsumption() {
        return result.getMemoryConsumption();
      }
      public Builder setMemoryConsumption(int value) {
        result.hasMemoryConsumption = true;
        result.memoryConsumption_ = value;
        return this;
      }
      public Builder clearMemoryConsumption() {
        result.hasMemoryConsumption = false;
        result.memoryConsumption_ = 0;
        return this;
      }
      
      // required int32 cpuConsumption = 4;
      public boolean hasCpuConsumption() {
        return result.hasCpuConsumption();
      }
      public int getCpuConsumption() {
        return result.getCpuConsumption();
      }
      public Builder setCpuConsumption(int value) {
        result.hasCpuConsumption = true;
        result.cpuConsumption_ = value;
        return this;
      }
      public Builder clearCpuConsumption() {
        result.hasCpuConsumption = false;
        result.cpuConsumption_ = 0;
        return this;
      }
      
      // required int32 memoryDemand = 5;
      public boolean hasMemoryDemand() {
        return result.hasMemoryDemand();
      }
      public int getMemoryDemand() {
        return result.getMemoryDemand();
      }
      public Builder setMemoryDemand(int value) {
        result.hasMemoryDemand = true;
        result.memoryDemand_ = value;
        return this;
      }
      public Builder clearMemoryDemand() {
        result.hasMemoryDemand = false;
        result.memoryDemand_ = 0;
        return this;
      }
      
      // required int32 cpuDemand = 6;
      public boolean hasCpuDemand() {
        return result.hasCpuDemand();
      }
      public int getCpuDemand() {
        return result.getCpuDemand();
      }
      public Builder setCpuDemand(int value) {
        result.hasCpuDemand = true;
        result.cpuDemand_ = value;
        return this;
      }
      public Builder clearCpuDemand() {
        result.hasCpuDemand = false;
        result.cpuDemand_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:VirtualMachine)
    }
    
    static {
      defaultInstance = new VirtualMachine(true);
      entropy.configuration.parser.PBVirtualMachine.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:VirtualMachine)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VirtualMachine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VirtualMachine_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%entropy/configuration/parser/vm.proto\"" +
      "\214\001\n\016VirtualMachine\022\014\n\004name\030\001 \002(\t\022\020\n\010nbOf" +
      "CPUs\030\002 \002(\005\022\031\n\021memoryConsumption\030\003 \002(\005\022\026\n" +
      "\016cpuConsumption\030\004 \002(\005\022\024\n\014memoryDemand\030\005 " +
      "\002(\005\022\021\n\tcpuDemand\030\006 \002(\005B0\n\034entropy.config" +
      "uration.parserB\020PBVirtualMachine"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VirtualMachine_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VirtualMachine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VirtualMachine_descriptor,
              new java.lang.String[] { "Name", "NbOfCPUs", "MemoryConsumption", "CpuConsumption", "MemoryDemand", "CpuDemand", },
              entropy.configuration.parser.PBVirtualMachine.VirtualMachine.class,
              entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
