// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entropy/configuration/parser/configuration.proto

package entropy.configuration.parser;

public final class PBConfiguration {
  private PBConfiguration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Configuration extends
      com.google.protobuf.GeneratedMessage {
    // Use Configuration.newBuilder() to construct.
    private Configuration() {
      initFields();
    }
    private Configuration(boolean noInit) {}
    
    private static final Configuration defaultInstance;
    public static Configuration getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public Configuration getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_fieldAccessorTable;
    }
    
    public enum HostedVMState
        implements com.google.protobuf.ProtocolMessageEnum {
      RUNNING(0, 0),
      SLEEPING(1, 2),
      ;
      
      
      @Override
	public final int getNumber() { return value; }
      
      public static HostedVMState valueOf(int value) {
        switch (value) {
          case 0: return RUNNING;
          case 2: return SLEEPING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<HostedVMState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<HostedVMState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HostedVMState>() {
              @Override
			public HostedVMState findValueByNumber(int number) {
                return HostedVMState.valueOf(number)
      ;        }
            };
      
      @Override
	public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      @Override
	public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return entropy.configuration.parser.PBConfiguration.Configuration.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final HostedVMState[] VALUES = {
        RUNNING, SLEEPING, 
      };
      public static HostedVMState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private HostedVMState(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        entropy.configuration.parser.PBConfiguration.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:Configuration.HostedVMState)
    }
    
    public static final class Hosted extends
        com.google.protobuf.GeneratedMessage {
      // Use Hosted.newBuilder() to construct.
      private Hosted() {
        initFields();
      }
      private Hosted(boolean noInit) {}
      
      private static final Hosted defaultInstance;
      public static Hosted getDefaultInstance() {
        return defaultInstance;
      }
      
      @Override
	public Hosted getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_Hosted_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_Hosted_fieldAccessorTable;
      }
      
      // required .VirtualMachine vm = 1;
      public static final int VM_FIELD_NUMBER = 1;
      private boolean hasVm;
      private entropy.configuration.parser.PBVirtualMachine.VirtualMachine vm_;
      public boolean hasVm() { return hasVm; }
      public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getVm() { return vm_; }
      
      // required .Configuration.HostedVMState state = 2;
      public static final int STATE_FIELD_NUMBER = 2;
      private boolean hasState;
      private entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState state_;
      public boolean hasState() { return hasState; }
      public entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState getState() { return state_; }
      
      private void initFields() {
        vm_ = entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance();
        state_ = entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState.RUNNING;
      }
      @Override
	public final boolean isInitialized() {
        if (!hasVm) return false;
        if (!hasState) return false;
        if (!getVm().isInitialized()) return false;
        return true;
      }
      
      @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasVm()) {
          output.writeMessage(1, getVm());
        }
        if (hasState()) {
          output.writeEnum(2, getState().getNumber());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      @Override
	public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasVm()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getVm());
        }
        if (hasState()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, getState().getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hosted parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      @Override
	public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(entropy.configuration.parser.PBConfiguration.Configuration.Hosted prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      @Override
	public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private entropy.configuration.parser.PBConfiguration.Configuration.Hosted result;
        
        // Construct using entropy.configuration.parser.PBConfiguration.Configuration.Hosted.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new entropy.configuration.parser.PBConfiguration.Configuration.Hosted();
          return builder;
        }
        
        @Override
		protected entropy.configuration.parser.PBConfiguration.Configuration.Hosted internalGetResult() {
          return result;
        }
        
        @Override
		public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new entropy.configuration.parser.PBConfiguration.Configuration.Hosted();
          return this;
        }
        
        @Override
		public Builder clone() {
          return create().mergeFrom(result);
        }
        
        @Override
		public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return entropy.configuration.parser.PBConfiguration.Configuration.Hosted.getDescriptor();
        }
        
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hosted getDefaultInstanceForType() {
          return entropy.configuration.parser.PBConfiguration.Configuration.Hosted.getDefaultInstance();
        }
        
        @Override
		public boolean isInitialized() {
          return result.isInitialized();
        }
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hosted build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private entropy.configuration.parser.PBConfiguration.Configuration.Hosted buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hosted buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          entropy.configuration.parser.PBConfiguration.Configuration.Hosted returnMe = result;
          result = null;
          return returnMe;
        }
        
        @Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof entropy.configuration.parser.PBConfiguration.Configuration.Hosted) {
            return mergeFrom((entropy.configuration.parser.PBConfiguration.Configuration.Hosted)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(entropy.configuration.parser.PBConfiguration.Configuration.Hosted other) {
          if (other == entropy.configuration.parser.PBConfiguration.Configuration.Hosted.getDefaultInstance()) return this;
          if (other.hasVm()) {
            mergeVm(other.getVm());
          }
          if (other.hasState()) {
            setState(other.getState());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        @Override
		public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder subBuilder = entropy.configuration.parser.PBVirtualMachine.VirtualMachine.newBuilder();
                if (hasVm()) {
                  subBuilder.mergeFrom(getVm());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setVm(subBuilder.buildPartial());
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState value = entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  setState(value);
                }
                break;
              }
            }
          }
        }
        
        
        // required .VirtualMachine vm = 1;
        public boolean hasVm() {
          return result.hasVm();
        }
        public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getVm() {
          return result.getVm();
        }
        public Builder setVm(entropy.configuration.parser.PBVirtualMachine.VirtualMachine value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasVm = true;
          result.vm_ = value;
          return this;
        }
        public Builder setVm(entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder builderForValue) {
          result.hasVm = true;
          result.vm_ = builderForValue.build();
          return this;
        }
        public Builder mergeVm(entropy.configuration.parser.PBVirtualMachine.VirtualMachine value) {
          if (result.hasVm() &&
              result.vm_ != entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance()) {
            result.vm_ =
              entropy.configuration.parser.PBVirtualMachine.VirtualMachine.newBuilder(result.vm_).mergeFrom(value).buildPartial();
          } else {
            result.vm_ = value;
          }
          result.hasVm = true;
          return this;
        }
        public Builder clearVm() {
          result.hasVm = false;
          result.vm_ = entropy.configuration.parser.PBVirtualMachine.VirtualMachine.getDefaultInstance();
          return this;
        }
        
        // required .Configuration.HostedVMState state = 2;
        public boolean hasState() {
          return result.hasState();
        }
        public entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState getState() {
          return result.getState();
        }
        public Builder setState(entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasState = true;
          result.state_ = value;
          return this;
        }
        public Builder clearState() {
          result.hasState = false;
          result.state_ = entropy.configuration.parser.PBConfiguration.Configuration.HostedVMState.RUNNING;
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:Configuration.Hosted)
      }
      
      static {
        defaultInstance = new Hosted(true);
        entropy.configuration.parser.PBConfiguration.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Configuration.Hosted)
    }
    
    public static final class Hoster extends
        com.google.protobuf.GeneratedMessage {
      // Use Hoster.newBuilder() to construct.
      private Hoster() {
        initFields();
      }
      private Hoster(boolean noInit) {}
      
      private static final Hoster defaultInstance;
      public static Hoster getDefaultInstance() {
        return defaultInstance;
      }
      
      @Override
	public Hoster getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_Hoster_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return entropy.configuration.parser.PBConfiguration.internal_static_Configuration_Hoster_fieldAccessorTable;
      }
      
      // required .Node node = 1;
      public static final int NODE_FIELD_NUMBER = 1;
      private boolean hasNode;
      private entropy.configuration.parser.PBNode.Node node_;
      public boolean hasNode() { return hasNode; }
      public entropy.configuration.parser.PBNode.Node getNode() { return node_; }
      
      // repeated .Configuration.Hosted hosted = 2;
      public static final int HOSTED_FIELD_NUMBER = 2;
      private java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hosted> hosted_ =
        java.util.Collections.emptyList();
      public java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hosted> getHostedList() {
        return hosted_;
      }
      public int getHostedCount() { return hosted_.size(); }
      public entropy.configuration.parser.PBConfiguration.Configuration.Hosted getHosted(int index) {
        return hosted_.get(index);
      }
      
      private void initFields() {
        node_ = entropy.configuration.parser.PBNode.Node.getDefaultInstance();
      }
      @Override
	public final boolean isInitialized() {
        if (!hasNode) return false;
        if (!getNode().isInitialized()) return false;
        for (entropy.configuration.parser.PBConfiguration.Configuration.Hosted element : getHostedList()) {
          if (!element.isInitialized()) return false;
        }
        return true;
      }
      
      @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasNode()) {
          output.writeMessage(1, getNode());
        }
        for (entropy.configuration.parser.PBConfiguration.Configuration.Hosted element : getHostedList()) {
          output.writeMessage(2, element);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      @Override
	public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasNode()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getNode());
        }
        for (entropy.configuration.parser.PBConfiguration.Configuration.Hosted element : getHostedList()) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, element);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static entropy.configuration.parser.PBConfiguration.Configuration.Hoster parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      @Override
	public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(entropy.configuration.parser.PBConfiguration.Configuration.Hoster prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      @Override
	public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private entropy.configuration.parser.PBConfiguration.Configuration.Hoster result;
        
        // Construct using entropy.configuration.parser.PBConfiguration.Configuration.Hoster.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new entropy.configuration.parser.PBConfiguration.Configuration.Hoster();
          return builder;
        }
        
        @Override
		protected entropy.configuration.parser.PBConfiguration.Configuration.Hoster internalGetResult() {
          return result;
        }
        
        @Override
		public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new entropy.configuration.parser.PBConfiguration.Configuration.Hoster();
          return this;
        }
        
        @Override
		public Builder clone() {
          return create().mergeFrom(result);
        }
        
        @Override
		public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return entropy.configuration.parser.PBConfiguration.Configuration.Hoster.getDescriptor();
        }
        
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hoster getDefaultInstanceForType() {
          return entropy.configuration.parser.PBConfiguration.Configuration.Hoster.getDefaultInstance();
        }
        
        @Override
		public boolean isInitialized() {
          return result.isInitialized();
        }
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hoster build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private entropy.configuration.parser.PBConfiguration.Configuration.Hoster buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        @Override
		public entropy.configuration.parser.PBConfiguration.Configuration.Hoster buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          if (result.hosted_ != java.util.Collections.EMPTY_LIST) {
            result.hosted_ =
              java.util.Collections.unmodifiableList(result.hosted_);
          }
          entropy.configuration.parser.PBConfiguration.Configuration.Hoster returnMe = result;
          result = null;
          return returnMe;
        }
        
        @Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof entropy.configuration.parser.PBConfiguration.Configuration.Hoster) {
            return mergeFrom((entropy.configuration.parser.PBConfiguration.Configuration.Hoster)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(entropy.configuration.parser.PBConfiguration.Configuration.Hoster other) {
          if (other == entropy.configuration.parser.PBConfiguration.Configuration.Hoster.getDefaultInstance()) return this;
          if (other.hasNode()) {
            mergeNode(other.getNode());
          }
          if (!other.hosted_.isEmpty()) {
            if (result.hosted_.isEmpty()) {
              result.hosted_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hosted>();
            }
            result.hosted_.addAll(other.hosted_);
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        @Override
		public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                entropy.configuration.parser.PBNode.Node.Builder subBuilder = entropy.configuration.parser.PBNode.Node.newBuilder();
                if (hasNode()) {
                  subBuilder.mergeFrom(getNode());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setNode(subBuilder.buildPartial());
                break;
              }
              case 18: {
                entropy.configuration.parser.PBConfiguration.Configuration.Hosted.Builder subBuilder = entropy.configuration.parser.PBConfiguration.Configuration.Hosted.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addHosted(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        
        // required .Node node = 1;
        public boolean hasNode() {
          return result.hasNode();
        }
        public entropy.configuration.parser.PBNode.Node getNode() {
          return result.getNode();
        }
        public Builder setNode(entropy.configuration.parser.PBNode.Node value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hasNode = true;
          result.node_ = value;
          return this;
        }
        public Builder setNode(entropy.configuration.parser.PBNode.Node.Builder builderForValue) {
          result.hasNode = true;
          result.node_ = builderForValue.build();
          return this;
        }
        public Builder mergeNode(entropy.configuration.parser.PBNode.Node value) {
          if (result.hasNode() &&
              result.node_ != entropy.configuration.parser.PBNode.Node.getDefaultInstance()) {
            result.node_ =
              entropy.configuration.parser.PBNode.Node.newBuilder(result.node_).mergeFrom(value).buildPartial();
          } else {
            result.node_ = value;
          }
          result.hasNode = true;
          return this;
        }
        public Builder clearNode() {
          result.hasNode = false;
          result.node_ = entropy.configuration.parser.PBNode.Node.getDefaultInstance();
          return this;
        }
        
        // repeated .Configuration.Hosted hosted = 2;
        public java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hosted> getHostedList() {
          return java.util.Collections.unmodifiableList(result.hosted_);
        }
        public int getHostedCount() {
          return result.getHostedCount();
        }
        public entropy.configuration.parser.PBConfiguration.Configuration.Hosted getHosted(int index) {
          return result.getHosted(index);
        }
        public Builder setHosted(int index, entropy.configuration.parser.PBConfiguration.Configuration.Hosted value) {
          if (value == null) {
            throw new NullPointerException();
          }
          result.hosted_.set(index, value);
          return this;
        }
        public Builder setHosted(int index, entropy.configuration.parser.PBConfiguration.Configuration.Hosted.Builder builderForValue) {
          result.hosted_.set(index, builderForValue.build());
          return this;
        }
        public Builder addHosted(entropy.configuration.parser.PBConfiguration.Configuration.Hosted value) {
          if (value == null) {
            throw new NullPointerException();
          }
          if (result.hosted_.isEmpty()) {
            result.hosted_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hosted>();
          }
          result.hosted_.add(value);
          return this;
        }
        public Builder addHosted(entropy.configuration.parser.PBConfiguration.Configuration.Hosted.Builder builderForValue) {
          if (result.hosted_.isEmpty()) {
            result.hosted_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hosted>();
          }
          result.hosted_.add(builderForValue.build());
          return this;
        }
        public Builder addAllHosted(
            java.lang.Iterable<? extends entropy.configuration.parser.PBConfiguration.Configuration.Hosted> values) {
          if (result.hosted_.isEmpty()) {
            result.hosted_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hosted>();
          }
          super.addAll(values, result.hosted_);
          return this;
        }
        public Builder clearHosted() {
          result.hosted_ = java.util.Collections.emptyList();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:Configuration.Hoster)
      }
      
      static {
        defaultInstance = new Hoster(true);
        entropy.configuration.parser.PBConfiguration.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Configuration.Hoster)
    }
    
    // repeated .Configuration.Hoster onlines = 1;
    public static final int ONLINES_FIELD_NUMBER = 1;
    private java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hoster> onlines_ =
      java.util.Collections.emptyList();
    public java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hoster> getOnlinesList() {
      return onlines_;
    }
    public int getOnlinesCount() { return onlines_.size(); }
    public entropy.configuration.parser.PBConfiguration.Configuration.Hoster getOnlines(int index) {
      return onlines_.get(index);
    }
    
    // repeated .Node offlines = 2;
    public static final int OFFLINES_FIELD_NUMBER = 2;
    private java.util.List<entropy.configuration.parser.PBNode.Node> offlines_ =
      java.util.Collections.emptyList();
    public java.util.List<entropy.configuration.parser.PBNode.Node> getOfflinesList() {
      return offlines_;
    }
    public int getOfflinesCount() { return offlines_.size(); }
    public entropy.configuration.parser.PBNode.Node getOfflines(int index) {
      return offlines_.get(index);
    }
    
    // repeated .VirtualMachine waitings = 3;
    public static final int WAITINGS_FIELD_NUMBER = 3;
    private java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine> waitings_ =
      java.util.Collections.emptyList();
    public java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine> getWaitingsList() {
      return waitings_;
    }
    public int getWaitingsCount() { return waitings_.size(); }
    public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getWaitings(int index) {
      return waitings_.get(index);
    }
    
    private void initFields() {
    }
    @Override
	public final boolean isInitialized() {
      for (entropy.configuration.parser.PBConfiguration.Configuration.Hoster element : getOnlinesList()) {
        if (!element.isInitialized()) return false;
      }
      for (entropy.configuration.parser.PBNode.Node element : getOfflinesList()) {
        if (!element.isInitialized()) return false;
      }
      for (entropy.configuration.parser.PBVirtualMachine.VirtualMachine element : getWaitingsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (entropy.configuration.parser.PBConfiguration.Configuration.Hoster element : getOnlinesList()) {
        output.writeMessage(1, element);
      }
      for (entropy.configuration.parser.PBNode.Node element : getOfflinesList()) {
        output.writeMessage(2, element);
      }
      for (entropy.configuration.parser.PBVirtualMachine.VirtualMachine element : getWaitingsList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (entropy.configuration.parser.PBConfiguration.Configuration.Hoster element : getOnlinesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (entropy.configuration.parser.PBNode.Node element : getOfflinesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      for (entropy.configuration.parser.PBVirtualMachine.VirtualMachine element : getWaitingsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBConfiguration.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(entropy.configuration.parser.PBConfiguration.Configuration prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private entropy.configuration.parser.PBConfiguration.Configuration result;
      
      // Construct using entropy.configuration.parser.PBConfiguration.Configuration.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new entropy.configuration.parser.PBConfiguration.Configuration();
        return builder;
      }
      
      @Override
	protected entropy.configuration.parser.PBConfiguration.Configuration internalGetResult() {
        return result;
      }
      
      @Override
	public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new entropy.configuration.parser.PBConfiguration.Configuration();
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(result);
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entropy.configuration.parser.PBConfiguration.Configuration.getDescriptor();
      }
      
      @Override
	public entropy.configuration.parser.PBConfiguration.Configuration getDefaultInstanceForType() {
        return entropy.configuration.parser.PBConfiguration.Configuration.getDefaultInstance();
      }
      
      @Override
	public boolean isInitialized() {
        return result.isInitialized();
      }
      @Override
	public entropy.configuration.parser.PBConfiguration.Configuration build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private entropy.configuration.parser.PBConfiguration.Configuration buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      @Override
	public entropy.configuration.parser.PBConfiguration.Configuration buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.onlines_ != java.util.Collections.EMPTY_LIST) {
          result.onlines_ =
            java.util.Collections.unmodifiableList(result.onlines_);
        }
        if (result.offlines_ != java.util.Collections.EMPTY_LIST) {
          result.offlines_ =
            java.util.Collections.unmodifiableList(result.offlines_);
        }
        if (result.waitings_ != java.util.Collections.EMPTY_LIST) {
          result.waitings_ =
            java.util.Collections.unmodifiableList(result.waitings_);
        }
        entropy.configuration.parser.PBConfiguration.Configuration returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entropy.configuration.parser.PBConfiguration.Configuration) {
          return mergeFrom((entropy.configuration.parser.PBConfiguration.Configuration)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(entropy.configuration.parser.PBConfiguration.Configuration other) {
        if (other == entropy.configuration.parser.PBConfiguration.Configuration.getDefaultInstance()) return this;
        if (!other.onlines_.isEmpty()) {
          if (result.onlines_.isEmpty()) {
            result.onlines_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hoster>();
          }
          result.onlines_.addAll(other.onlines_);
        }
        if (!other.offlines_.isEmpty()) {
          if (result.offlines_.isEmpty()) {
            result.offlines_ = new java.util.ArrayList<entropy.configuration.parser.PBNode.Node>();
          }
          result.offlines_.addAll(other.offlines_);
        }
        if (!other.waitings_.isEmpty()) {
          if (result.waitings_.isEmpty()) {
            result.waitings_ = new java.util.ArrayList<entropy.configuration.parser.PBVirtualMachine.VirtualMachine>();
          }
          result.waitings_.addAll(other.waitings_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              entropy.configuration.parser.PBConfiguration.Configuration.Hoster.Builder subBuilder = entropy.configuration.parser.PBConfiguration.Configuration.Hoster.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOnlines(subBuilder.buildPartial());
              break;
            }
            case 18: {
              entropy.configuration.parser.PBNode.Node.Builder subBuilder = entropy.configuration.parser.PBNode.Node.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOfflines(subBuilder.buildPartial());
              break;
            }
            case 26: {
              entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder subBuilder = entropy.configuration.parser.PBVirtualMachine.VirtualMachine.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addWaitings(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .Configuration.Hoster onlines = 1;
      public java.util.List<entropy.configuration.parser.PBConfiguration.Configuration.Hoster> getOnlinesList() {
        return java.util.Collections.unmodifiableList(result.onlines_);
      }
      public int getOnlinesCount() {
        return result.getOnlinesCount();
      }
      public entropy.configuration.parser.PBConfiguration.Configuration.Hoster getOnlines(int index) {
        return result.getOnlines(index);
      }
      public Builder setOnlines(int index, entropy.configuration.parser.PBConfiguration.Configuration.Hoster value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.onlines_.set(index, value);
        return this;
      }
      public Builder setOnlines(int index, entropy.configuration.parser.PBConfiguration.Configuration.Hoster.Builder builderForValue) {
        result.onlines_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOnlines(entropy.configuration.parser.PBConfiguration.Configuration.Hoster value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.onlines_.isEmpty()) {
          result.onlines_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hoster>();
        }
        result.onlines_.add(value);
        return this;
      }
      public Builder addOnlines(entropy.configuration.parser.PBConfiguration.Configuration.Hoster.Builder builderForValue) {
        if (result.onlines_.isEmpty()) {
          result.onlines_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hoster>();
        }
        result.onlines_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOnlines(
          java.lang.Iterable<? extends entropy.configuration.parser.PBConfiguration.Configuration.Hoster> values) {
        if (result.onlines_.isEmpty()) {
          result.onlines_ = new java.util.ArrayList<entropy.configuration.parser.PBConfiguration.Configuration.Hoster>();
        }
        super.addAll(values, result.onlines_);
        return this;
      }
      public Builder clearOnlines() {
        result.onlines_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .Node offlines = 2;
      public java.util.List<entropy.configuration.parser.PBNode.Node> getOfflinesList() {
        return java.util.Collections.unmodifiableList(result.offlines_);
      }
      public int getOfflinesCount() {
        return result.getOfflinesCount();
      }
      public entropy.configuration.parser.PBNode.Node getOfflines(int index) {
        return result.getOfflines(index);
      }
      public Builder setOfflines(int index, entropy.configuration.parser.PBNode.Node value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.offlines_.set(index, value);
        return this;
      }
      public Builder setOfflines(int index, entropy.configuration.parser.PBNode.Node.Builder builderForValue) {
        result.offlines_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOfflines(entropy.configuration.parser.PBNode.Node value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.offlines_.isEmpty()) {
          result.offlines_ = new java.util.ArrayList<entropy.configuration.parser.PBNode.Node>();
        }
        result.offlines_.add(value);
        return this;
      }
      public Builder addOfflines(entropy.configuration.parser.PBNode.Node.Builder builderForValue) {
        if (result.offlines_.isEmpty()) {
          result.offlines_ = new java.util.ArrayList<entropy.configuration.parser.PBNode.Node>();
        }
        result.offlines_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOfflines(
          java.lang.Iterable<? extends entropy.configuration.parser.PBNode.Node> values) {
        if (result.offlines_.isEmpty()) {
          result.offlines_ = new java.util.ArrayList<entropy.configuration.parser.PBNode.Node>();
        }
        super.addAll(values, result.offlines_);
        return this;
      }
      public Builder clearOfflines() {
        result.offlines_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .VirtualMachine waitings = 3;
      public java.util.List<entropy.configuration.parser.PBVirtualMachine.VirtualMachine> getWaitingsList() {
        return java.util.Collections.unmodifiableList(result.waitings_);
      }
      public int getWaitingsCount() {
        return result.getWaitingsCount();
      }
      public entropy.configuration.parser.PBVirtualMachine.VirtualMachine getWaitings(int index) {
        return result.getWaitings(index);
      }
      public Builder setWaitings(int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.waitings_.set(index, value);
        return this;
      }
      public Builder setWaitings(int index, entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder builderForValue) {
        result.waitings_.set(index, builderForValue.build());
        return this;
      }
      public Builder addWaitings(entropy.configuration.parser.PBVirtualMachine.VirtualMachine value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.waitings_.isEmpty()) {
          result.waitings_ = new java.util.ArrayList<entropy.configuration.parser.PBVirtualMachine.VirtualMachine>();
        }
        result.waitings_.add(value);
        return this;
      }
      public Builder addWaitings(entropy.configuration.parser.PBVirtualMachine.VirtualMachine.Builder builderForValue) {
        if (result.waitings_.isEmpty()) {
          result.waitings_ = new java.util.ArrayList<entropy.configuration.parser.PBVirtualMachine.VirtualMachine>();
        }
        result.waitings_.add(builderForValue.build());
        return this;
      }
      public Builder addAllWaitings(
          java.lang.Iterable<? extends entropy.configuration.parser.PBVirtualMachine.VirtualMachine> values) {
        if (result.waitings_.isEmpty()) {
          result.waitings_ = new java.util.ArrayList<entropy.configuration.parser.PBVirtualMachine.VirtualMachine>();
        }
        super.addAll(values, result.waitings_);
        return this;
      }
      public Builder clearWaitings() {
        result.waitings_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Configuration)
    }
    
    static {
      defaultInstance = new Configuration(true);
      entropy.configuration.parser.PBConfiguration.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Configuration)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configuration_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_Hosted_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configuration_Hosted_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Configuration_Hoster_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Configuration_Hoster_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0entropy/configuration/parser/configura" +
      "tion.proto\032\'entropy/configuration/parser" +
      "/node.proto\032%entropy/configuration/parse" +
      "r/vm.proto\"\271\002\n\rConfiguration\022&\n\007onlines\030" +
      "\001 \003(\0132\025.Configuration.Hoster\022\027\n\010offlines" +
      "\030\002 \003(\0132\005.Node\022!\n\010waitings\030\003 \003(\0132\017.Virtua" +
      "lMachine\032R\n\006Hosted\022\033\n\002vm\030\001 \002(\0132\017.Virtual" +
      "Machine\022+\n\005state\030\002 \002(\0162\034.Configuration.H" +
      "ostedVMState\032D\n\006Hoster\022\023\n\004node\030\001 \002(\0132\005.N" +
      "ode\022%\n\006hosted\030\002 \003(\0132\025.Configuration.Host",
      "ed\"*\n\rHostedVMState\022\013\n\007RUNNING\020\000\022\014\n\010SLEE" +
      "PING\020\002B/\n\034entropy.configuration.parserB\017" +
      "PBConfiguration"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Configuration_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Configuration_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Configuration_descriptor,
              new java.lang.String[] { "Onlines", "Offlines", "Waitings", },
              entropy.configuration.parser.PBConfiguration.Configuration.class,
              entropy.configuration.parser.PBConfiguration.Configuration.Builder.class);
          internal_static_Configuration_Hosted_descriptor =
            internal_static_Configuration_descriptor.getNestedTypes().get(0);
          internal_static_Configuration_Hosted_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Configuration_Hosted_descriptor,
              new java.lang.String[] { "Vm", "State", },
              entropy.configuration.parser.PBConfiguration.Configuration.Hosted.class,
              entropy.configuration.parser.PBConfiguration.Configuration.Hosted.Builder.class);
          internal_static_Configuration_Hoster_descriptor =
            internal_static_Configuration_descriptor.getNestedTypes().get(1);
          internal_static_Configuration_Hoster_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Configuration_Hoster_descriptor,
              new java.lang.String[] { "Node", "Hosted", },
              entropy.configuration.parser.PBConfiguration.Configuration.Hoster.class,
              entropy.configuration.parser.PBConfiguration.Configuration.Hoster.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          entropy.configuration.parser.PBNode.getDescriptor(),
          entropy.configuration.parser.PBVirtualMachine.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
