// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entropy/configuration/parser/node.proto

package entropy.configuration.parser;

public final class PBNode {
  private PBNode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Node extends
      com.google.protobuf.GeneratedMessage {
    // Use Node.newBuilder() to construct.
    private Node() {
      initFields();
    }
    private Node(boolean noInit) {}
    
    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return entropy.configuration.parser.PBNode.internal_static_Node_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return entropy.configuration.parser.PBNode.internal_static_Node_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 nbOfCPUs = 2;
    public static final int NBOFCPUS_FIELD_NUMBER = 2;
    private boolean hasNbOfCPUs;
    private int nbOfCPUs_ = 0;
    public boolean hasNbOfCPUs() { return hasNbOfCPUs; }
    public int getNbOfCPUs() { return nbOfCPUs_; }
    
    // required int32 memoryCapacity = 3;
    public static final int MEMORYCAPACITY_FIELD_NUMBER = 3;
    private boolean hasMemoryCapacity;
    private int memoryCapacity_ = 0;
    public boolean hasMemoryCapacity() { return hasMemoryCapacity; }
    public int getMemoryCapacity() { return memoryCapacity_; }
    
    // required int32 cpuCapacity = 4;
    public static final int CPUCAPACITY_FIELD_NUMBER = 4;
    private boolean hasCpuCapacity;
    private int cpuCapacity_ = 0;
    public boolean hasCpuCapacity() { return hasCpuCapacity; }
    public int getCpuCapacity() { return cpuCapacity_; }
    
    private void initFields() {
    }
    @Override
	public final boolean isInitialized() {
      if (!hasName) return false;
      if (!hasNbOfCPUs) return false;
      if (!hasMemoryCapacity) return false;
      if (!hasCpuCapacity) return false;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasNbOfCPUs()) {
        output.writeInt32(2, getNbOfCPUs());
      }
      if (hasMemoryCapacity()) {
        output.writeInt32(3, getMemoryCapacity());
      }
      if (hasCpuCapacity()) {
        output.writeInt32(4, getCpuCapacity());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      if (hasNbOfCPUs()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getNbOfCPUs());
      }
      if (hasMemoryCapacity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getMemoryCapacity());
      }
      if (hasCpuCapacity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getCpuCapacity());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBNode.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static entropy.configuration.parser.PBNode.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(entropy.configuration.parser.PBNode.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private entropy.configuration.parser.PBNode.Node result;
      
      // Construct using entropy.configuration.parser.PBNode.Node.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new entropy.configuration.parser.PBNode.Node();
        return builder;
      }
      
      @Override
	protected entropy.configuration.parser.PBNode.Node internalGetResult() {
        return result;
      }
      
      @Override
	public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new entropy.configuration.parser.PBNode.Node();
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(result);
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return entropy.configuration.parser.PBNode.Node.getDescriptor();
      }
      
      @Override
	public entropy.configuration.parser.PBNode.Node getDefaultInstanceForType() {
        return entropy.configuration.parser.PBNode.Node.getDefaultInstance();
      }
      
      @Override
	public boolean isInitialized() {
        return result.isInitialized();
      }
      @Override
	public entropy.configuration.parser.PBNode.Node build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private entropy.configuration.parser.PBNode.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      @Override
	public entropy.configuration.parser.PBNode.Node buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        entropy.configuration.parser.PBNode.Node returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof entropy.configuration.parser.PBNode.Node) {
          return mergeFrom((entropy.configuration.parser.PBNode.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(entropy.configuration.parser.PBNode.Node other) {
        if (other == entropy.configuration.parser.PBNode.Node.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasNbOfCPUs()) {
          setNbOfCPUs(other.getNbOfCPUs());
        }
        if (other.hasMemoryCapacity()) {
          setMemoryCapacity(other.getMemoryCapacity());
        }
        if (other.hasCpuCapacity()) {
          setCpuCapacity(other.getCpuCapacity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 16: {
              setNbOfCPUs(input.readInt32());
              break;
            }
            case 24: {
              setMemoryCapacity(input.readInt32());
              break;
            }
            case 32: {
              setCpuCapacity(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required int32 nbOfCPUs = 2;
      public boolean hasNbOfCPUs() {
        return result.hasNbOfCPUs();
      }
      public int getNbOfCPUs() {
        return result.getNbOfCPUs();
      }
      public Builder setNbOfCPUs(int value) {
        result.hasNbOfCPUs = true;
        result.nbOfCPUs_ = value;
        return this;
      }
      public Builder clearNbOfCPUs() {
        result.hasNbOfCPUs = false;
        result.nbOfCPUs_ = 0;
        return this;
      }
      
      // required int32 memoryCapacity = 3;
      public boolean hasMemoryCapacity() {
        return result.hasMemoryCapacity();
      }
      public int getMemoryCapacity() {
        return result.getMemoryCapacity();
      }
      public Builder setMemoryCapacity(int value) {
        result.hasMemoryCapacity = true;
        result.memoryCapacity_ = value;
        return this;
      }
      public Builder clearMemoryCapacity() {
        result.hasMemoryCapacity = false;
        result.memoryCapacity_ = 0;
        return this;
      }
      
      // required int32 cpuCapacity = 4;
      public boolean hasCpuCapacity() {
        return result.hasCpuCapacity();
      }
      public int getCpuCapacity() {
        return result.getCpuCapacity();
      }
      public Builder setCpuCapacity(int value) {
        result.hasCpuCapacity = true;
        result.cpuCapacity_ = value;
        return this;
      }
      public Builder clearCpuCapacity() {
        result.hasCpuCapacity = false;
        result.cpuCapacity_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Node)
    }
    
    static {
      defaultInstance = new Node(true);
      entropy.configuration.parser.PBNode.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Node)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Node_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'entropy/configuration/parser/node.prot" +
      "o\"S\n\004Node\022\014\n\004name\030\001 \002(\t\022\020\n\010nbOfCPUs\030\002 \002(" +
      "\005\022\026\n\016memoryCapacity\030\003 \002(\005\022\023\n\013cpuCapacity" +
      "\030\004 \002(\005B&\n\034entropy.configuration.parserB\006" +
      "PBNode"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Node_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Node_descriptor,
              new java.lang.String[] { "Name", "NbOfCPUs", "MemoryCapacity", "CpuCapacity", },
              entropy.configuration.parser.PBNode.Node.class,
              entropy.configuration.parser.PBNode.Node.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
